/* Generated from the approved Wearables.html showcase — 12 products, in display order. */
import type { ShowcaseItem } from "./showcase-types";

export const wearables: ShowcaseItem[] = [
  {
    id: "smart-glasses",
    name: "Smart Glasses",
    intro: "Augmented Reality (AR) and AI converge to transform wearable technology. Equipped with advanced sensors for gesture control, mixed reality, and hands-free operation, Smart Glasses deliver real-time assistance and productivity through <span class=\"caipo\">CAIPO</span> integration.",
    detail: {
      name: "Smart Glasses",
      title: "Smart Glasses",
      intro: "Augmented Reality (AR) and AI converge to transform wearable technology. Equipped with advanced sensors for gesture control, mixed reality, and hands-free operation, Smart Glasses deliver real-time assistance and productivity through <span class=\"caipo\">CAIPO</span> integration.",
      mcTitle: "Smart Glasses <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "When paired with MoodChanger.ai, Smart Glasses go beyond function and help users enhance focus, relaxation, and emotional well-being in any environment.",
      tagline: "Real-time assistance + AI support <span class=\"ar\">=</span> <span class=\"ans\">better focus, calmer states, stronger productivity</span>",
    },
    capabilities: [
      { icon: "<path d=\"M12 3a3 3 0 0 1 3 3v5a3 3 0 0 1-6 0V6a3 3 0 0 1 3-3z\"/><path d=\"M5 11a7 7 0 0 0 14 0M12 18v3\"/>", title: "Voice Commands", body: "Control your world hands-free" },
      { icon: "<path d=\"m8 7-5 5 5 5M16 7l5 5-5 5\"/>", title: "Developer Friendly", body: "Open-source platform" },
      { icon: "<path d=\"m12 3 9 5-9 5-9-5 9-5z\"/><path d=\"m3 13 9 5 9-5\"/>", title: "Mixed Reality", body: "Seamless digital overlays" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Hands-free access to patient data for surgeons or medical staff." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Real-time performance stats, navigation, or tactical insights during games." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Augmented reality (AR) overlays for workflow management or multitasking." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Immersive experiences or calming environments projected through AR to influence emotional states." },
    ],
  },
  {
    id: "eeg-hardware",
    name: "EEG Hardware",
    intro: "EEG Hardware monitors brain activity in real time, providing insights into mental states, cognitive performance, and stress.",
    detail: {
      name: "EEG Hardware",
      title: "EEG Hardware",
      intro: "EEG Hardware monitors brain activity in real time, providing insights into mental states, cognitive performance, and stress.",
      mcTitle: "EEG Hardware <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "Integrated with <span class=\"caipo\">CAIPO</span>, it enhances focus and productivity by identifying peak mental performance periods. Through MoodChanger.ai, it leverages neurofeedback to promote relaxation and emotional balance.",
      tagline: "Real-time brain activity + neurofeedback <span class=\"ar\">=</span> <span class=\"ans\">stronger focus and emotional balance</span>",
    },
    capabilities: [
      { icon: "<rect x=\"2\" y=\"8\" width=\"17\" height=\"8\" rx=\"2\"/><path d=\"M22 11v2M5.5 11v2M9 11v2\"/>", title: "Battery Life", body: "Extended operational time" },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4zM19 16l.8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8z\"/>", title: "Software Integration", body: "Compatible with applications" },
      { icon: "<path d=\"M2 12h3l2-6 3 12 2.5-8 2 5H22\"/>", title: "EEG Signal Monitoring", body: "Tracks brainwave activity" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Use in neurological assessments, mental health therapies." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Brainwave analysis to improve performance through mental training." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Enhancing concentration and cognitive efficiency based on real-time feedback." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Targeted audio stimulation or biofeedback for mood improvement." },
    ],
  },
  {
    id: "smart-ring",
    name: "Smart Ring",
    intro: "Compact and stylish wearable that tracks health metrics such as heart rate, sleep patterns, and stress levels.",
    detail: {
      name: "Smart Ring",
      title: "Smart Ring",
      intro: "Compact and stylish wearable that tracks health metrics such as heart rate, sleep patterns, and stress levels.",
      mcTitle: "Smart Ring <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "With <span class=\"caipo\">CAIPO</span>, it provides actionable insights to improve wellness and streamline productivity through gesture-based controls. MoodChanger.ai integrates with the ring's haptic feedback to deliver calming vibrations and manage stress effectively.",
      tagline: "Wearable biometrics + haptic feedback <span class=\"ar\">=</span> <span class=\"ans\">smarter wellness and better emotional balance</span>",
    },
    capabilities: [
      { icon: "<circle cx=\"14\" cy=\"5\" r=\"1.8\"/><path d=\"M9 20l2.5-5L9 12l3-4 3 2.5 3 .5M11 8 8 9.5 6.5 12\"/>", title: "Activity Tracking", body: "Daily activity logs" },
      { icon: "<path d=\"M12 3s6 6.5 6 11a6 6 0 0 1-12 0c0-4.5 6-11 6-11z\"/>", title: "Water Resistance", body: "Durable against moisture" },
      { icon: "<path d=\"M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6\"/><path d=\"M10.5 20a1.7 1.7 0 0 0 3 0\"/>", title: "Customizable Alerts", body: "Personalized notifications setup" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Monitoring vital signs and sleep patterns." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Track activity, heart rate and movement patterns." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Quick gesture-based controls, notifications, and more." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Vibrations for stress management or mood alerts." },
    ],
  },
  {
    id: "brain-monitor",
    name: "Brain Monitoring",
    intro: "Products that provide real-time brain activity analysis. With <span class=\"caipo\">CAIPO</span>, they assist in improving cognitive performance and reducing mental fatigue.",
    detail: {
      name: "Brain Monitoring",
      title: "Brain Monitoring",
      intro: "Products that provide real-time brain activity analysis. With <span class=\"caipo\">CAIPO</span>, they assist in improving cognitive performance and reducing mental fatigue.",
      mcTitle: "Brain Monitoring <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "MoodChanger.ai uses the data to provide relaxation exercises and biofeedback for stress relief and emotional regulation.",
      tagline: "Real-time brain activity + biofeedback <span class=\"ar\">=</span> <span class=\"ans\">sharper focus and better emotional balance</span>",
    },
    capabilities: [
      { icon: "<path d=\"M4 14v-3a8 8 0 0 1 16 0v3\"/><rect x=\"3\" y=\"14\" width=\"4\" height=\"6\" rx=\"1.5\"/><rect x=\"17\" y=\"14\" width=\"4\" height=\"6\" rx=\"1.5\"/>", title: "Headband", body: "Instant data insights. Real-time feedback." },
      { icon: "<path d=\"M4 14v-3a8 8 0 0 1 16 0v3\"/><rect x=\"3\" y=\"14\" width=\"4\" height=\"6\" rx=\"1.5\"/><rect x=\"17\" y=\"14\" width=\"4\" height=\"6\" rx=\"1.5\"/>", title: "Headphones", body: "Durable against moisture. Water resistant." },
      { icon: "<path d=\"M4 14v-3a8 8 0 0 1 16 0v3\"/><rect x=\"3\" y=\"14\" width=\"4\" height=\"6\" rx=\"1.5\"/><rect x=\"17\" y=\"14\" width=\"4\" height=\"6\" rx=\"1.5\"/>", title: "Baseball Cap", body: "Wireless connectivity. Seamless data transfer" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Support mental health assessments and personalized therapy." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Enhance focus and performance with neurofeedback and mindfulness exercises." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Improve focus and reduce stress through real-time feedback." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Promote relaxation and emotional balance with biofeedback." },
    ],
  },
  {
    id: "smart-foot-pods",
    name: "Smart Foot Pods",
    intro: "Advanced wearables for runners, offering insights into biomechanics, running power, and performance metrics.",
    detail: {
      name: "Smart Foot Pods",
      title: "Smart Foot Pods",
      intro: "Advanced wearables for runners, offering insights into biomechanics, running power, and performance metrics.",
      mcTitle: "Smart Foot Pods <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "<span class=\"caipo\">CAIPO</span> enhances these devices by providing personalized training recommendations and progress tracking. With MoodChanger.ai, they create a motivational environment to keep users focused and engaged in achieving their fitness goals.",
      tagline: "Biomechanics + AI coaching <span class=\"ar\">=</span> <span class=\"ans\">measurable progress and stronger motivation</span>",
    },
    capabilities: [
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8z\"/>", title: "Power Measurement", body: "Tracks energy output" },
      { icon: "<path d=\"M3 12h4l2-5 3 10 2.5-7 1.5 2h5\"/>", title: "Fitness Tracking", body: "Step frequency measurement" },
      { icon: "<circle cx=\"12\" cy=\"12\" r=\"8\"/><circle cx=\"12\" cy=\"12\" r=\"4\"/><circle cx=\"12\" cy=\"12\" r=\"1\" fill=\"currentColor\" stroke=\"none\"/>", title: "Impact Analysis", body: "Assesses foot pressure" },
    ],
    applications: [
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Movement tracking, running technique monitoring, and injury prevention." },
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Motion monitoring for elderly patients or people in physical therapy." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Posture tracking or movement efficiency for reducing strain during daily activities." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Gentle reminders to move, combined with biofeedback, to uplift energy levels or manage fatigue." },
    ],
  },
  {
    id: "smart-insoles",
    name: "Smart Insoles",
    intro: "Designed for gait analysis, posture improvement, and health monitoring.",
    detail: {
      name: "Smart Insoles",
      title: "Smart Insoles",
      intro: "Designed for gait analysis, posture improvement, and health monitoring.",
      mcTitle: "Smart Insoles <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "<span class=\"caipo\">CAIPO</span> leverages their data to optimize movement efficiency, reduce fatigue, and support rehabilitation. MoodChanger.ai complements these features by providing subtle biofeedback to encourage activity and uplift energy levels.",
      tagline: "Gait intelligence + subtle biofeedback <span class=\"ar\">=</span> <span class=\"ans\">better movement and higher energy</span>",
    },
    capabilities: [
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8z\"/>", title: "Power Measurement", body: "Tracks energy output" },
      { icon: "<path d=\"M3 12h4l2-5 3 10 2.5-7 1.5 2h5\"/>", title: "Fitness Tracking", body: "Step frequency measurement" },
      { icon: "<circle cx=\"12\" cy=\"12\" r=\"8\"/><circle cx=\"12\" cy=\"12\" r=\"4\"/><circle cx=\"12\" cy=\"12\" r=\"1\" fill=\"currentColor\" stroke=\"none\"/>", title: "Impact Analysis", body: "Assesses foot pressure" },
    ],
    applications: [
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Movement tracking, running technique monitoring, and injury prevention." },
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Motion monitoring for elderly patients or people in physical therapy." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Posture tracking or movement efficiency for reducing strain during daily activities." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Gentle reminders to move, combined with biofeedback, to uplift energy levels or manage fatigue." },
    ],
  },
  {
    id: "smart-watch",
    name: "Smart Watch",
    intro: "Customizable device offering fitness tracking, heart rate monitoring, and GPS navigation.",
    detail: {
      name: "Smart Watch",
      title: "Smart Watch",
      intro: "Customizable device offering fitness tracking, heart rate monitoring, and GPS navigation.",
      mcTitle: "Smart Watch <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "Integrated with <span class=\"caipo\">CAIPO</span>, it enables seamless task management and real-time data visualization. MoodChanger.ai enhances the user experience with stress tracking, guided breathing exercises, and reminders for maintaining emotional balance.",
      tagline: "Fitness tracking + AI support <span class=\"ar\">=</span> <span class=\"ans\">stronger performance and emotional balance</span>",
    },
    capabilities: [
      { icon: "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/><path d=\"M12 7v5l3.2 2\"/>", title: "Customizable Watchfaces", body: "Personalized display options" },
      { icon: "<path d=\"M3 12h4l2-5 3 10 2.5-7 1.5 2h5\"/>", title: "Fitness Tracking", body: "Activity monitoring included" },
      { icon: "<rect x=\"4\" y=\"4\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"13\" y=\"4\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"4\" y=\"13\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"13\" y=\"13\" width=\"7\" height=\"7\" rx=\"1.5\"/>", title: "App Integration", body: "Compatible with phone apps" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Continuous health monitoring." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Heart rate monitoring, GPS tracking, and performance analytics." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Task management, reminders, and communication control on the go." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Stress tracking, guided breathing exercises, and sleep improvement." },
    ],
  },
  {
    id: "exoskeleton",
    name: "Exoskeleton",
    intro: "A revolutionary body measurement system that uses 3D scanning to deliver accurate data for fitness and health tracking.",
    detail: {
      name: "Exoskeleton",
      title: "Exoskeleton",
      intro: "A revolutionary body measurement system that uses 3D scanning to deliver accurate data for fitness and health tracking.",
      mcTitle: "Exoskeleton <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "With <span class=\"caipo\">CAIPO</span> it provides insights for personalized recommendations and ergonomic improvements. MoodChanger.ai leverages its tracking capabilities to motivate users and enhance self-confidence through visual progress tracking.",
      tagline: "3D scanning + AI recommendations <span class=\"ar\">=</span> <span class=\"ans\">stronger mobility and confident progress</span>",
    },
    capabilities: [
      { icon: "<path d=\"M4.3 6.3a4.5 4.5 0 0 0 0 6.4L12 20.4l7.7-7.7a4.5 4.5 0 0 0-6.4-6.4L12 7.6l-1.3-1.3a4.5 4.5 0 0 0-6.4 0z\"/>", title: "Heart Rate Monitoring", body: "Tracks heart variability" },
      { icon: "<circle cx=\"12\" cy=\"12\" r=\"7\"/><path d=\"M12 2v4M12 18v4M2 12h4M18 12h4\"/>", title: "Respiration Tracking", body: "Measures breathing volume." },
      { icon: "<circle cx=\"14\" cy=\"5\" r=\"1.8\"/><path d=\"M9 20l2.5-5L9 12l3-4 3 2.5 3 .5M11 8 8 9.5 6.5 12\"/>", title: "Activity Tracking", body: "Monitors movement" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Assistance for patients with mobility impairments or in physical rehabilitation." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Enhancing physical abilities for rehabilitation training or performance enhancement." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Reducing physical strain in industrial or manual labor tasks." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Improved mobility and reduced physical stress can positively impact mental health and well-being." },
    ],
  },
  {
    id: "smart-gloves",
    name: "Smart Gloves",
    intro: "Wearable device designed for precise motion tracking and gesture control.",
    detail: {
      name: "Smart Gloves",
      title: "Smart Gloves",
      intro: "Wearable device designed for precise motion tracking and gesture control.",
      mcTitle: "Smart Gloves <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "With <span class=\"caipo\">CAIPO</span>, it transforms workflows by enabling seamless device navigation and remote operation for complex tasks. MoodChanger.ai enhances its functionality by providing haptic feedback to improve user interaction, offering an engaging and calming experience for training or productivity.",
      tagline: "Gesture control + haptic feedback <span class=\"ar\">=</span> <span class=\"ans\">precise interaction and calmer performance</span>",
    },
    capabilities: [
      { icon: "<path d=\"M8 13V6.5a1.5 1.5 0 0 1 3 0V11m0-.5V4.6a1.5 1.5 0 0 1 3 0V11m0-.2V6.6a1.5 1.5 0 0 1 3 0V14c0 3.4-2.2 6-5.4 6h-.8c-1.7 0-2.7-.7-3.7-1.8L6 14.6c-.8-1 .6-2.6 1.7-1.7L9 14\"/>", title: "Gesture Control", body: "Enables seamless navigation" },
      { icon: "<rect x=\"9\" y=\"5\" width=\"6\" height=\"14\" rx=\"1.5\"/><path d=\"M5 9v6M3 10.5v3M19 9v6M21 10.5v3\"/>", title: "Haptic Feedback", body: "Immersive and interactive" },
      { icon: "<circle cx=\"12\" cy=\"12\" r=\"7\"/><path d=\"M12 2v4M12 18v4M2 12h4M18 12h4\"/>", title: "Precision Tracking", body: "Accurate control" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Rehabilitation for hand mobility, stroke recovery, or motor skill training." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Motion tracking for sports like golf or boxing to enhance training." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Gesture controls for seamless device navigation." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Biofeedback through touch, vibration feedback, or temperature regulation to influence mood." },
    ],
  },
  {
    id: "smart-shirt",
    name: "Smart Shirt",
    intro: "Tracks heart rate, respiration, activity, and sleep. Its seamless integration with mobile apps provides real-time insights into physical performance.",
    detail: {
      name: "Smart Shirt",
      title: "Smart Shirt",
      intro: "Tracks heart rate, respiration, activity, and sleep. Its seamless integration with mobile apps provides real-time insights into physical performance.",
      mcTitle: "Smart Shirt <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "<span class=\"caipo\">CAIPO</span> uses this data to improve productivity and fitness outcomes, while MoodChanger.ai focuses on stress monitoring and providing relaxation techniques.",
      tagline: "Continuous vital tracking + AI guidance <span class=\"ar\">=</span> <span class=\"ans\">stronger performance and emotional balance</span>",
    },
    capabilities: [
      { icon: "<path d=\"M4.3 6.3a4.5 4.5 0 0 0 0 6.4L12 20.4l7.7-7.7a4.5 4.5 0 0 0-6.4-6.4L12 7.6l-1.3-1.3a4.5 4.5 0 0 0-6.4 0z\"/>", title: "Heart Rate Monitoring", body: "Tracks heart variability" },
      { icon: "<circle cx=\"12\" cy=\"12\" r=\"7\"/><path d=\"M12 2v4M12 18v4M2 12h4M18 12h4\"/>", title: "Respiration Tracking", body: "Measures breathing volume" },
      { icon: "<circle cx=\"14\" cy=\"5\" r=\"1.8\"/><path d=\"M9 20l2.5-5L9 12l3-4 3 2.5 3 .5M11 8 8 9.5 6.5 12\"/>", title: "Activity Tracking", body: "Monitors steps and movement" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Continuous monitoring of vital signs, particularly in patients with heart or respiratory conditions." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Tracks heart rate, breathing, and movement for in-depth performance insights." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Posture correction and physical activity tracking." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Real-time monitoring of stress levels, providing insights into emotional well-being." },
    ],
  },
  {
    id: "smart-suit",
    name: "Smart Suit",
    intro: "Revolutionary body measurement system that uses 3D scanning to deliver accurate data for fitness and health tracking.",
    detail: {
      name: "Smart Suit",
      title: "Smart Suit",
      intro: "Revolutionary body measurement system that uses 3D scanning to deliver accurate data for fitness and health tracking.",
      mcTitle: "Smart Suit <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "With <span class=\"caipo\">CAIPO</span>, it provides insights for personalized recommendations and ergonomic improvements. MoodChanger.ai uses its tracking capabilities to motivate users and enhance self-confidence through visual progress tracking.",
      tagline: "3D body tracking + AI insights <span class=\"ar\">=</span> <span class=\"ans\">measurable progress and stronger confidence</span>",
    },
    capabilities: [
      { icon: "<path d=\"M4.3 6.3a4.5 4.5 0 0 0 0 6.4L12 20.4l7.7-7.7a4.5 4.5 0 0 0-6.4-6.4L12 7.6l-1.3-1.3a4.5 4.5 0 0 0-6.4 0z\"/>", title: "Heart Rate Monitoring", body: "Tracks heart variability" },
      { icon: "<circle cx=\"12\" cy=\"12\" r=\"7\"/><path d=\"M12 2v4M12 18v4M2 12h4M18 12h4\"/>", title: "Respiration Tracking", body: "Measures breathing volume" },
      { icon: "<path d=\"M12 2v20M2 12h20M12 2l-3 3M12 2l3 3M12 22l-3-3M12 22l3-3M2 12l3-3M2 12l3 3M22 12l-3-3M22 12l-3 3\"/>", title: "Monitors movement", body: "Tracks posture and motion" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Assesses body composition for health monitoring." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Tracks body measurements for fitness progress." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Motivates with visual progress tracking." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Enhances self-image with body change feedback." },
    ],
  },
  {
    id: "smart-posture-trainer",
    name: "Smart Posture Trainer",
    intro: "Equipped with advanced wearable sensors to help users improve back health and overall posture.",
    detail: {
      name: "Smart Posture Trainer",
      title: "Smart Posture Trainer",
      intro: "Equipped with advanced wearable sensors to help users improve back health and overall posture.",
      mcTitle: "Smart Posture Trainer <span class=\"plus\">+ MoodChanger.ai</span>",
      mcBody: "With real-time feedback and personalized training, this device builds healthier habits for better physical alignment. Connected to <span class=\"caipo\">CAIPO</span>, it improves posture at work, while MoodChanger.ai provides gentle reminders to reduce stress and encourage calmness.",
      tagline: "Posture feedback + AI guidance <span class=\"ar\">=</span> <span class=\"ans\">healthier alignment and calmer routines</span>",
    },
    capabilities: [
      { icon: "<path d=\"M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6\"/><path d=\"M10.5 20a1.7 1.7 0 0 0 3 0\"/>", title: "Custom Vibration Alert", body: "Adjustable slouch reminders" },
      { icon: "<path d=\"M8.5 3 12 6l3.5-3 4.5 3.2-2 4.3-2-1V21H8V12.5l-2 1-2-4.3z\"/>", title: "Wearable Flexibility", body: "Can be worn discreetly" },
      { icon: "<rect x=\"2\" y=\"8\" width=\"17\" height=\"8\" rx=\"2\"/><path d=\"M22 11v2M5.5 11v2M9 11v2\"/>", title: "30-hour Battery", body: "Extended daily use" },
    ],
    applications: [
      { icon: "<path d=\"M3 12h3.2l1.8 5 3.8-12 2.3 7H21\"/>", title: "Healthcare", body: "Support weight management and rehabilitation with detailed body tracking." },
      { icon: "<path d=\"M13 2 5 13h6l-1 9 8-12h-6l1-8Z\"/>", title: "Sports", body: "Monitor body measurements to improve fitness and optimize training plans." },
      { icon: "<path d=\"M4 4v16h16M8 14l3-3 3 3 5-6\"/>", title: "Productivity", body: "Enhance workplace comfort with posture and movement analysis." },
      { icon: "<path d=\"M12 3l1.9 5.6L19 10l-5.1 1.4L12 17l-1.9-5.6L5 10l5.1-1.4Z\"/>", title: "Mood Changing", body: "Boost confidence and motivation with progress visualization." },
    ],
  },
];
